# Generated by Django 3.2.8 on 2022-03-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
