# Generated by Django 3.2.8 on 2022-02-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_sellerdetail_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='seller_slider_img')),
                ('url', models.CharField(default='#', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='photo',
            field=models.ImageField(default='/User_photos/default.png', upload_to='User_photos'),
        ),
    ]
