# Generated by Django 3.2.8 on 2022-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_productsize_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
    ]
