# Generated by Django 3.2.8 on 2022-02-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_alter_sellerdetail_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='categoey_name',
        ),
    ]
