# Generated by Django 3.2.8 on 2022-03-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_auto_20220228_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='products/images/'),
        ),
    ]
