# Generated by Django 3.2.8 on 2022-02-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
